basePath: /api/v1
definitions:
  domain.Asset:
    properties:
      default_location:
        type: string
      id:
        type: integer
      item_master_id:
        type: integer
      last_check_date:
        type: string
      last_checker:
        type: string
      location:
        type: string
      notes:
        type: string
      owner:
        type: string
      purchase_date:
        type: string
      quantity:
        type: integer
      serial_number:
        type: string
      status_id:
        type: integer
    type: object
  domain.AssetMaster:
    properties:
      genre_id:
        type: integer
      id:
        type: integer
      management_category_id:
        type: integer
      manufacturer:
        type: string
      model_number:
        type: string
      name:
        type: string
    type: object
  domain.AssetsLend:
    properties:
      actual_return_date:
        description: 実際の返却日 ("YYYY-MM-DD" or null)
        type: string
      asset_id:
        description: 貸出対象資産ID
        type: integer
      borrower:
        description: 借用者
        type: string
      expected_return_date:
        description: 返却予定日 ("YYYY-MM-DD" or null)
        type: string
      id:
        description: 主キー
        type: integer
      lend_date:
        description: 貸出日 ("YYYY-MM-DD")
        type: string
      notes:
        description: 備考 (null可)
        type: string
      quantity:
        description: 貸出数
        type: integer
    type: object
  domain.CreateAssetRequest:
    properties:
      asset_master_id:
        description: '--- マスター情報（任意） ---'
        type: integer
      default_location:
        type: string
      genre_id:
        type: integer
      last_check_date:
        type: string
      last_checker:
        type: string
      management_category_id:
        type: integer
      manufacturer:
        type: string
      model_number:
        type: string
      name:
        type: string
      notes:
        type: string
      owner:
        type: string
      purchase_date:
        description: '(形式: "YYYY-MM-DD")'
        type: string
      quantity:
        description: '--- 個別資産情報 ---'
        type: integer
      serial_number:
        type: string
      status_id:
        type: integer
    required:
    - quantity
    - status_id
    type: object
  domain.CreateDisposalRequest:
    properties:
      is_individual:
        description: 個別管理かどうか
        type: boolean
      processed_by:
        description: 処理者の学籍番号
        type: string
      quantity:
        type: integer
      reason:
        type: string
    type: object
  domain.DisposalResponse:
    properties:
      asset_id:
        description: 対象資産 ID
        type: integer
      disposal_date:
        description: 廃棄日 (YYYY-MM-DD)
        type: string
      id:
        description: 主キー
        type: integer
      processed_by:
        description: 処理担当者
        type: string
      quantity:
        description: 廃棄数量
        type: integer
      reason:
        description: 廃棄理由
        type: string
    type: object
  domain.EditAssetRequest:
    properties:
      asset_id:
        description: 主キー
        type: integer
      last_check_date:
        type: string
      last_checker:
        type: string
      location:
        type: string
      notes:
        type: string
      owner:
        type: string
      purchase_date:
        type: string
      quantity:
        description: 更新時は任意
        type: integer
      serial_number:
        type: string
      status_id:
        description: 更新時は任意, IDなのでint64
        type: integer
    type: object
  domain.EditLendRequest:
    properties:
      actual_return_date:
        description: NULL 可（通常登録時はNULL）
        type: string
      borrower:
        type: string
      expected_return_date:
        description: NULL 可
        type: string
      lend_date:
        description: '"YYYY-MM-DD" 形式'
        type: string
      notes:
        description: NULL 可
        type: string
      quantity:
        type: integer
    required:
    - borrower
    - lend_date
    - quantity
    type: object
  domain.LendAssetRequest:
    properties:
      actual_return_date:
        description: NULL 可（通常登録時はNULL）
        type: string
      asset_id:
        type: integer
      borrower:
        type: string
      expected_return_date:
        description: NULL 可
        type: string
      lend_date:
        description: '"YYYY-MM-DD" 形式'
        type: string
      notes:
        description: NULL 可
        type: string
      quantity:
        type: integer
    required:
    - asset_id
    - borrower
    - lend_date
    - quantity
    type: object
  domain.LendingDetail:
    properties:
      borrower:
        type: string
      expected_return_date:
        type: string
      id:
        type: integer
      lend_date:
        type: string
      manufacturer:
        type: string
      model_number:
        type: string
      name:
        type: string
      notes:
        type: string
      quantity:
        type: integer
    type: object
  domain.ReturnAssetRequest:
    properties:
      actual_return_date:
        type: string
      lendID:
        type: integer
      notes:
        description: NULL 可
        type: string
      quantity:
        description: 返却数量
        type: integer
    required:
    - actual_return_date
    - quantity
    type: object
  handler.AssetListResponse:
    properties:
      assets:
        items:
          $ref: '#/definitions/domain.Asset'
        type: array
      message:
        example: Assets fetched successfully
        type: string
    type: object
  handler.AssetMasterListResponse:
    properties:
      masters:
        items:
          $ref: '#/definitions/domain.AssetMaster'
        type: array
      message:
        example: Asset masters fetched successfully
        type: string
    type: object
  handler.AssetMasterResponse:
    properties:
      master:
        $ref: '#/definitions/domain.AssetMaster'
      message:
        example: Asset master fetched successfully
        type: string
    type: object
  handler.AssetResponse:
    properties:
      asset:
        $ref: '#/definitions/domain.Asset'
      message:
        example: Asset fetched successfully
        type: string
    type: object
  handler.CreateAssetResponse:
    properties:
      asset_master_id:
        example: 101
        type: integer
      message:
        example: Asset created successfully
        type: string
    type: object
  handler.DisposalListResponse:
    properties:
      disposals:
        items:
          $ref: '#/definitions/domain.DisposalResponse'
        type: array
      message:
        example: Disposals fetched successfully
        type: string
    type: object
  handler.DisposalResponseWrapper:
    properties:
      disposal:
        $ref: '#/definitions/domain.DisposalResponse'
      message:
        example: Disposal fetched successfully
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      error:
        example: 不正なリクエストです
        type: string
    type: object
  handler.LendListResponse:
    properties:
      lends:
        items:
          $ref: '#/definitions/domain.AssetsLend'
        type: array
    type: object
  handler.LendResponse:
    properties:
      lend:
        $ref: '#/definitions/domain.AssetsLend'
      message:
        example: Fetch completed
        type: string
    type: object
  handler.LendingDetailListResponse:
    properties:
      lends:
        items:
          $ref: '#/definitions/domain.LendingDetail'
        type: array
    type: object
  handler.PingErrorResponse:
    properties:
      error:
        example: Internal Server Error
        type: string
    type: object
  handler.PingResponse:
    properties:
      message:
        example: pong
        type: string
    type: object
  handler.SuccessResponse:
    properties:
      message:
        example: 処理に成功しました
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: 研究室内の備品を管理するシステムです。
  title: 備品管理システム
  version: "1.0"
paths:
  /assets:
    post:
      consumes:
      - application/json
      description: 資産マスター情報と個別資産情報を同時に作成します。
      parameters:
      - description: 資産作成リクエスト
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.CreateAssetRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.CreateAssetResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 資産の新規作成
      tags:
      - Asset
  /assets/{id}:
    get:
      description: 指定されたIDの個別資産情報を取得します。
      parameters:
      - description: 資産ID (Asset ID)
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.AssetResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 資産情報の取得 (ID指定)
      tags:
      - Asset
  /assets/all:
    get:
      description: 登録されている全ての個別資産情報を取得します。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.AssetListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 全資産の一覧取得
      tags:
      - Asset
  /assets/edit/{id}:
    put:
      consumes:
      - application/json
      description: 指定されたIDの個別資産情報を更新します。
      parameters:
      - description: 資産ID (Asset ID)
        in: path
        name: id
        required: true
        type: integer
      - description: 資産更新リクエスト
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.EditAssetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 資産情報の更新
      tags:
      - Asset
  /assets/master/{id}:
    delete:
      description: 指定されたIDの資産マスター情報を削除します。
      parameters:
      - description: 資産マスターID (Asset Master ID)
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 資産マスター情報の削除
      tags:
      - Asset Master
    get:
      description: 指定されたIDの資産マスター情報を取得します。
      parameters:
      - description: 資産マスターID (Asset Master ID)
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.AssetMasterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 資産マスター情報の取得 (ID指定)
      tags:
      - Asset Master
  /assets/master/all:
    get:
      description: 登録されている全ての資産マスター情報を取得します。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.AssetMasterListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 全資産マスターの一覧取得
      tags:
      - Asset Master
  /disposal/{id}:
    get:
      description: 指定されたIDの廃棄履歴を取得します。
      parameters:
      - description: 廃棄ID (Disposal ID)
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.DisposalResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 廃棄履歴の取得 (ID指定)
      tags:
      - Disposal
    post:
      consumes:
      - application/json
      description: 指定された資産IDの資産を廃棄登録します。
      parameters:
      - description: 資産ID (Asset ID)
        in: path
        name: id
        required: true
        type: integer
      - description: 廃棄登録リクエスト
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.CreateDisposalRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 資産の廃棄処理
      tags:
      - Disposal
  /disposal/all:
    get:
      description: 全ての資産廃棄履歴を取得します。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.DisposalListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 全廃棄履歴の取得
      tags:
      - Disposal
  /lend/{id}:
    get:
      parameters:
      - description: 貸出ID (Lend ID)
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.LendResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 貸出情報取得 (ID指定)
      tags:
      - Lend
    post:
      consumes:
      - application/json
      parameters:
      - description: 備品ID (Asset ID)
        in: path
        name: id
        required: true
        type: integer
      - description: 貸出情報
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.LendAssetRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 備品貸出処理
      tags:
      - Lend
  /lend/all:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.LendListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 貸出情報一覧取得
      tags:
      - Lend
  /lend/all/with-name:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.LendingDetailListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 貸出情報一覧取得 (名称付き)
      tags:
      - Lend
  /lend/edit/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: 貸出ID (Lend ID)
        in: path
        name: id
        required: true
        type: integer
      - description: 更新情報
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.EditLendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 貸出情報編集
      tags:
      - Lend
  /lend/return/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: 貸出ID (Lend ID)
        in: path
        name: id
        required: true
        type: integer
      - description: 返却情報
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.ReturnAssetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 備品返却処理
      tags:
      - Lend
  /ping:
    get:
      description: Ping応答を確認するためのハンドラー.そもそもswaggerが動いていればpongは絶対返ってくるはず。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.PingResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.PingErrorResponse'
      summary: Ping応答を確認
      tags:
      - system
swagger: "2.0"
